# Generated by Django 2.1.7 on 2023-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligma',
            name='date',
            field=models.DateField(default='1111-01-01'),
        ),
        migrations.AlterField(
            model_name='ligma',
            name='desc',
            field=models.TextField(default='very cool items'),
        ),
        migrations.AlterField(
            model_name='ligma',
            name='price',
            field=models.BigIntegerField(default=69.99),
        ),
        migrations.AlterField(
            model_name='ligma',
            name='title',
            field=models.TextField(default='Bruh'),
        ),
    ]
