# Generated by Django 2.1.7 on 2023-06-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20230619_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ligma',
            new_name='TestModel',
        ),
    ]
