# Generated by Django 2.1.7 on 2023-06-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230608_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
