# Generated by Django 2.1.7 on 2022-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('driver', models.CharField(max_length=15)),
                ('tagNumber', models.CharField(max_length=15)),
            ],
        ),
    ]
