# Generated by Django 2.1.7 on 2022-06-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surf',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
