# Generated by Django 2.1.7 on 2022-06-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0002_surf_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surf',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
