# Generated by Django 2.1.7 on 2022-06-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0003_auto_20220616_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surf',
            name='summary',
            field=models.TextField(),
        ),
    ]
