# Generated by Django 2.1.7 on 2023-06-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.TextField(default=None)),
                ('order_date', models.TimeField(default=None)),
                ('shipped_date', models.TimeField(default=None)),
                ('product_ordered', models.TimeField(default=None)),
                ('product_number', models.TextField(default=None)),
            ],
        ),
    ]
