# Generated by Django 2.1.7 on 2023-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230608_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.TimeField(default=None),
        ),
    ]
